In [55]:
import pandas

file_obce = 'sldb2021_vek5_pohlavi.csv'
df_obce = pandas.read_csv(file_obce, encoding='utf-8')
df_obce

,idhod,hodnota,ukaz_kod,vek_cis,vek_kod,pohlavi_cis,pohlavi_kod,uzemi_cis,uzemi_kod,sldb_rok,sldb_datum,ukaz_txt,vek_txt,pohlavi_txt,uzemi_txt
0,947108883,1817,3162,NaN,NaN,NaN,NaN,43,500011,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,NaN,NaN,Želechovice nad Dřevnicí
1,947084833,909,3162,NaN,NaN,102.0,1.0,43,500011,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,NaN,muž,Želechovice nad Dřevnicí
2,947119976,908,3162,NaN,NaN,102.0,2.0,43,500011,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,NaN,žena,Želechovice nad Dřevnicí
3,964961283,93,3162,1035.0,1.100000e+09,NaN,NaN,43,500011,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,0 - 4 roky,NaN,Želechovice nad Dřevnicí
4,964734134,60,3162,1035.0,1.100000e+09,102.0,1.0,43,500011,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,0 - 4 roky,muž,Želechovice nad Dřevnicí
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
443779,964612411,340,3162,1035.0,1.300950e+09,102.0,1.0,101,40924,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,95 - 99 let,muž,Praha
443780,964683828,1251,3162,1035.0,1.300950e+09,102.0,2.0,101,40924,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,95 - 99 let,žena,Praha
443781,964631895,118,3162,1035.0,1.201010e+09,NaN,NaN,101,40924,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,100 a více let,NaN,Praha
443782,964669271,22,3162,1035.0,1.201010e+09,102.0,1.0,101,40924,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,100 a více let,muž,Praha
443783,964683740,96,3162,1035.0,1.201010e+09,102.0,2.0,101,40924,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,100 a více let,žena,Praha

## Filtruji věkové kategorie
##### Pro kontrolu hledám unikátní hodnoty a jejich počet v některých sloupcích

In [56]:
unikatni_vek_kod = df_obce['vek_kod'].unique()
print(unikatni_vek_kod, len(unikatni_vek_kod))

[           nan 1.10000000e+09 1.30005001e+09 1.30010001e+09
 1.30015002e+09 1.30020002e+09 1.30025003e+09 1.30030003e+09
 1.30035004e+09 1.30040004e+09 1.30045005e+09 1.30050005e+09
 1.30055006e+09 1.30060006e+09 1.30065007e+09 1.30070007e+09
 1.30075008e+09 1.30080008e+09 1.30085009e+09 1.30090009e+09
 1.30095010e+09 1.20101000e+09] 22

In [57]:
unikatni_vek_txt = df_obce['vek_txt'].unique()
print(unikatni_vek_txt, len(unikatni_vek_txt))

[nan '0 - 4 roky' '5 - 9 let' '10 - 14 let' '15 - 19 let' '20 - 24 let'
 '25 - 29 let' '30 - 34 let' '35 - 39 let' '40 - 44 let' '45 - 49 let'
 '50 - 54 let' '55 - 59 let' '60 - 64 let' '65 - 69 let' '70 - 74 let'
 '75 - 79 let' '80 - 84 let' '85 - 89 let' '90 - 94 let' '95 - 99 let'
 '100 a více let'] 22

##### Co znamená nan u věku? Kolik jich je?
NaN = celkem bez ohledu na věk, M, F (= 3 kategorie, ostatní věky taky mají tři kategorie - celkem, M, F)

In [58]:
df_obce['vek_kod'].isna().sum()

20172

##### Číselník pro věkovou kategorii 15-19: 1300150019

In [59]:
df_obce_teenageri = df_obce[df_obce['vek_kod'] == 1300150019]
df_obce_teenageri

,idhod,hodnota,ukaz_kod,vek_cis,vek_kod,pohlavi_cis,pohlavi_kod,uzemi_cis,uzemi_kod,sldb_rok,sldb_datum,ukaz_txt,vek_txt,pohlavi_txt,uzemi_txt
12,965126809,78,3162,1035.0,1.300150e+09,NaN,NaN,43,500011,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,15 - 19 let,NaN,Želechovice nad Dřevnicí
13,965229933,50,3162,1035.0,1.300150e+09,102.0,1.0,43,500011,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,15 - 19 let,muž,Želechovice nad Dřevnicí
14,965064695,28,3162,1035.0,1.300150e+09,102.0,2.0,43,500011,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,15 - 19 let,žena,Želechovice nad Dřevnicí
78,965209522,60,3162,1035.0,1.300150e+09,NaN,NaN,43,500020,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,15 - 19 let,NaN,Petrov nad Desnou
79,964734422,24,3162,1035.0,1.300150e+09,102.0,1.0,43,500020,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,15 - 19 let,muž,Petrov nad Desnou
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
443665,964612162,7602,3162,1035.0,1.300150e+09,102.0,1.0,101,40916,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,15 - 19 let,muž,Ostrava-město
443666,964669437,7227,3162,1035.0,1.300150e+09,102.0,2.0,101,40916,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,15 - 19 let,žena,Ostrava-město
443730,964661642,50866,3162,1035.0,1.300150e+09,NaN,NaN,101,40924,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,15 - 19 let,NaN,Praha
443731,964655193,25776,3162,1035.0,1.300150e+09,102.0,1.0,101,40924,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,15 - 19 let,muž,Praha
443732,964612413,25090,3162,1035.0,1.300150e+09,102.0,2.0,101,40924,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,15 - 19 let,žena,Praha

##### Věkových kategorií je 21 + celkem bez ohledu na věk

In [60]:
443784 / 22  # kontrola

20172.0

## Filtruji hodnoty pro obě pohlaví dohromady
pohlavi_kod = NaN

In [61]:
unikatni_pohlavi_txt = df_obce['pohlavi_txt'].unique()
print(unikatni_pohlavi_txt, len(unikatni_pohlavi_txt))

[nan 'muž' 'žena'] 3

In [62]:
unikatni_pohlavi_kod = df_obce['pohlavi_kod'].unique()
print(unikatni_pohlavi_kod, len(unikatni_pohlavi_kod))

[nan  1.  2.] 3

In [63]:
df_obce_teenageri_bezpohlavni = df_obce_teenageri[df_obce_teenageri['pohlavi_kod'].isna()]
df_obce_teenageri_bezpohlavni

,idhod,hodnota,ukaz_kod,vek_cis,vek_kod,pohlavi_cis,pohlavi_kod,uzemi_cis,uzemi_kod,sldb_rok,sldb_datum,ukaz_txt,vek_txt,pohlavi_txt,uzemi_txt
12,965126809,78,3162,1035.0,1.300150e+09,NaN,NaN,43,500011,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,15 - 19 let,NaN,Želechovice nad Dřevnicí
78,965209522,60,3162,1035.0,1.300150e+09,NaN,NaN,43,500020,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,15 - 19 let,NaN,Petrov nad Desnou
144,965127119,80,3162,1035.0,1.300150e+09,NaN,NaN,43,500046,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,15 - 19 let,NaN,Libhošť
210,965292413,115,3162,1035.0,1.300150e+09,NaN,NaN,43,500062,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,15 - 19 let,NaN,Krhová
276,964959498,89,3162,1035.0,1.300150e+09,NaN,NaN,43,500071,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,15 - 19 let,NaN,Poličná
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
443466,964632862,11065,3162,1035.0,1.300150e+09,NaN,NaN,101,40886,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,15 - 19 let,NaN,Karviná
443532,964675956,7231,3162,1035.0,1.300150e+09,NaN,NaN,101,40894,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,15 - 19 let,NaN,Nový Jičín
443598,964661082,8492,3162,1035.0,1.300150e+09,NaN,NaN,101,40908,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,15 - 19 let,NaN,Opava
443664,964662483,14829,3162,1035.0,1.300150e+09,NaN,NaN,101,40916,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,15 - 19 let,NaN,Ostrava-město
443730,964661642,50866,3162,1035.0,1.300150e+09,NaN,NaN,101,40924,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,15 - 19 let,NaN,Praha

In [64]:
20172 / 3  # kontrola

6724.0

##### Kontrola, že věky i pohlaví mají jedinou hodnotu

In [65]:
df_obce_teenageri_bezpohlavni['vek_kod'].unique()

array([1.30015002e+09])

In [66]:
df_obce_teenageri_bezpohlavni['pohlavi_kod'].unique()

array([nan])

## Můžu smazat všechny sloupce pohlaví a věků

In [67]:
df_obce_teenageri_bezpohlavni = df_obce_teenageri_bezpohlavni.drop(['pohlavi_kod', 'vek_cis', 'vek_kod', 'pohlavi_cis', 'pohlavi_txt', 'sldb_datum', 'vek_txt'], axis=1)
df_obce_teenageri_bezpohlavni

,idhod,hodnota,ukaz_kod,uzemi_cis,uzemi_kod,sldb_rok,ukaz_txt,uzemi_txt
12,965126809,78,3162,43,500011,2021,Počet obyvatel s obvyklým pobytem,Želechovice nad Dřevnicí
78,965209522,60,3162,43,500020,2021,Počet obyvatel s obvyklým pobytem,Petrov nad Desnou
144,965127119,80,3162,43,500046,2021,Počet obyvatel s obvyklým pobytem,Libhošť
210,965292413,115,3162,43,500062,2021,Počet obyvatel s obvyklým pobytem,Krhová
276,964959498,89,3162,43,500071,2021,Počet obyvatel s obvyklým pobytem,Poličná
...,...,...,...,...,...,...,...,...
443466,964632862,11065,3162,101,40886,2021,Počet obyvatel s obvyklým pobytem,Karviná
443532,964675956,7231,3162,101,40894,2021,Počet obyvatel s obvyklým pobytem,Nový Jičín
443598,964661082,8492,3162,101,40908,2021,Počet obyvatel s obvyklým pobytem,Opava
443664,964662483,14829,3162,101,40916,2021,Počet obyvatel s obvyklým pobytem,Ostrava-město
443730,964661642,50866,3162,101,40924,2021,Počet obyvatel s obvyklým pobytem,Praha

## Filtruji hodnoty pro kraje

In [68]:
unikatni_uzemi_cis = df_obce['uzemi_cis'].unique()
print(unikatni_uzemi_cis, len(unikatni_uzemi_cis))

[ 43  44  65  72  97  99 100 101] 8

##### Číselník pro kraj: 100, okres: 101, správní obvody obcí s rozšířenou působností: 65, správní obvody v hlavním městě: 72

In [69]:
df_kraje = df_obce_teenageri_bezpohlavni[df_obce_teenageri_bezpohlavni['uzemi_cis'] == 100]
df_kraje

,idhod,hodnota,ukaz_kod,uzemi_cis,uzemi_kod,sldb_rok,ukaz_txt,uzemi_txt
437790,964588472,50866,3162,100,3018,2021,Počet obyvatel s obvyklým pobytem,Hlavní město Praha
437856,964592498,68354,3162,100,3026,2021,Počet obyvatel s obvyklým pobytem,Středočeský kraj
437922,964591925,30082,3162,100,3034,2021,Počet obyvatel s obvyklým pobytem,Jihočeský kraj
437988,964593061,26476,3162,100,3042,2021,Počet obyvatel s obvyklým pobytem,Plzeňský kraj
438054,964591360,13508,3162,100,3051,2021,Počet obyvatel s obvyklým pobytem,Karlovarský kraj
438120,964594780,40442,3162,100,3069,2021,Počet obyvatel s obvyklým pobytem,Ústecký kraj
438186,964597072,20785,3162,100,3077,2021,Počet obyvatel s obvyklým pobytem,Liberecký kraj
438252,964594199,25634,3162,100,3085,2021,Počet obyvatel s obvyklým pobytem,Královéhradecký kraj
438318,964593625,24395,3162,100,3093,2021,Počet obyvatel s obvyklým pobytem,Pardubický kraj
438384,964596494,24108,3162,100,3107,2021,Počet obyvatel s obvyklým pobytem,Kraj Vysočina
438450,964595915,53245,3162,100,3115,2021,Počet obyvatel s obvyklým pobytem,Jihomoravský kraj
438516,964589636,29198,3162,100,3123,2021,Počet obyvatel s obvyklým pobytem,Olomoucký kraj
438582,964589051,26667,3162,100,3131,2021,Počet obyvatel s obvyklým pobytem,Zlínský kraj
438648,964590783,56076,3162,100,3140,2021,Počet obyvatel s obvyklým pobytem,Moravskoslezský kraj

## Ukládám tabulku podle krajů

In [70]:
df_kraje = df_kraje.reset_index(drop=True)  # reset index, drop původní index, PK je IDHOD + UZEMI_KOD
df_kraje

,idhod,hodnota,ukaz_kod,uzemi_cis,uzemi_kod,sldb_rok,ukaz_txt,uzemi_txt
0,964588472,50866,3162,100,3018,2021,Počet obyvatel s obvyklým pobytem,Hlavní město Praha
1,964592498,68354,3162,100,3026,2021,Počet obyvatel s obvyklým pobytem,Středočeský kraj
2,964591925,30082,3162,100,3034,2021,Počet obyvatel s obvyklým pobytem,Jihočeský kraj
3,964593061,26476,3162,100,3042,2021,Počet obyvatel s obvyklým pobytem,Plzeňský kraj
4,964591360,13508,3162,100,3051,2021,Počet obyvatel s obvyklým pobytem,Karlovarský kraj
5,964594780,40442,3162,100,3069,2021,Počet obyvatel s obvyklým pobytem,Ústecký kraj
6,964597072,20785,3162,100,3077,2021,Počet obyvatel s obvyklým pobytem,Liberecký kraj
7,964594199,25634,3162,100,3085,2021,Počet obyvatel s obvyklým pobytem,Královéhradecký kraj
8,964593625,24395,3162,100,3093,2021,Počet obyvatel s obvyklým pobytem,Pardubický kraj
9,964596494,24108,3162,100,3107,2021,Počet obyvatel s obvyklým pobytem,Kraj Vysočina
10,964595915,53245,3162,100,3115,2021,Počet obyvatel s obvyklým pobytem,Jihomoravský kraj
11,964589636,29198,3162,100,3123,2021,Počet obyvatel s obvyklým pobytem,Olomoucký kraj
12,964589051,26667,3162,100,3131,2021,Počet obyvatel s obvyklým pobytem,Zlínský kraj
13,964590783,56076,3162,100,3140,2021,Počet obyvatel s obvyklým pobytem,Moravskoslezský kraj

In [71]:
df_kraje.to_csv('teenageri_kraje.csv')

## Filtruji hodnoty pro okresy a nahrazuju Prahu za 22 městských obvodů
ČR má 76 okresů (#101), Praha není okres, Praha má 22 správních obvodů (P1-22, #72)

In [72]:
df_okresy = df_obce_teenageri_bezpohlavni[df_obce_teenageri_bezpohlavni['uzemi_cis'] == 101]
df_okresy

,idhod,hodnota,ukaz_kod,uzemi_cis,uzemi_kod,sldb_rok,ukaz_txt,uzemi_txt
438714,964632166,4628,3162,101,40169,2021,Počet obyvatel s obvyklým pobytem,Benešov
438780,964704572,4485,3162,101,40177,2021,Počet obyvatel s obvyklým pobytem,Beroun
438846,964675015,7941,3162,101,40185,2021,Počet obyvatel s obvyklým pobytem,Kladno
438912,964703858,4882,3162,101,40193,2021,Počet obyvatel s obvyklým pobytem,Kolín
438978,964618666,3332,3162,101,40207,2021,Počet obyvatel s obvyklým pobytem,Kutná Hora
...,...,...,...,...,...,...,...,...
443466,964632862,11065,3162,101,40886,2021,Počet obyvatel s obvyklým pobytem,Karviná
443532,964675956,7231,3162,101,40894,2021,Počet obyvatel s obvyklým pobytem,Nový Jičín
443598,964661082,8492,3162,101,40908,2021,Počet obyvatel s obvyklým pobytem,Opava
443664,964662483,14829,3162,101,40916,2021,Počet obyvatel s obvyklým pobytem,Ostrava-město
443730,964661642,50866,3162,101,40924,2021,Počet obyvatel s obvyklým pobytem,Praha

In [74]:
df_okresy = df_okresy[df_okresy['uzemi_kod'] != 40924]  # 40924 = uzemi_kod pro Prahu
df_okresy

,idhod,hodnota,ukaz_kod,uzemi_cis,uzemi_kod,sldb_rok,ukaz_txt,uzemi_txt
438714,964632166,4628,3162,101,40169,2021,Počet obyvatel s obvyklým pobytem,Benešov
438780,964704572,4485,3162,101,40177,2021,Počet obyvatel s obvyklým pobytem,Beroun
438846,964675015,7941,3162,101,40185,2021,Počet obyvatel s obvyklým pobytem,Kladno
438912,964703858,4882,3162,101,40193,2021,Počet obyvatel s obvyklým pobytem,Kolín
438978,964618666,3332,3162,101,40207,2021,Počet obyvatel s obvyklým pobytem,Kutná Hora
...,...,...,...,...,...,...,...,...
443400,964704695,10124,3162,101,40878,2021,Počet obyvatel s obvyklým pobytem,Frýdek-Místek
443466,964632862,11065,3162,101,40886,2021,Počet obyvatel s obvyklým pobytem,Karviná
443532,964675956,7231,3162,101,40894,2021,Počet obyvatel s obvyklým pobytem,Nový Jičín
443598,964661082,8492,3162,101,40908,2021,Počet obyvatel s obvyklým pobytem,Opava
443664,964662483,14829,3162,101,40916,2021,Počet obyvatel s obvyklým pobytem,Ostrava-město

In [73]:
df_praha = df_obce_teenageri_bezpohlavni[df_obce_teenageri_bezpohlavni['uzemi_cis'] == 72]
df_praha

,idhod,hodnota,ukaz_kod,uzemi_cis,uzemi_kod,sldb_rok,ukaz_txt,uzemi_txt
435744,964964065,968,3162,72,1101,2021,Počet obyvatel s obvyklým pobytem,Praha 1
435810,965294207,1721,3162,72,1102,2021,Počet obyvatel s obvyklým pobytem,Praha 2
435876,965129597,2561,3162,72,1103,2021,Počet obyvatel s obvyklým pobytem,Praha 3
435942,964881412,5371,3162,72,1104,2021,Počet obyvatel s obvyklým pobytem,Praha 4
436008,964963828,3605,3162,72,1105,2021,Počet obyvatel s obvyklým pobytem,Praha 5
436074,965294264,4628,3162,72,1106,2021,Počet obyvatel s obvyklým pobytem,Praha 6
436140,964798598,1515,3162,72,1107,2021,Počet obyvatel s obvyklým pobytem,Praha 7
436206,965046394,4514,3162,72,1108,2021,Počet obyvatel s obvyklým pobytem,Praha 8
436272,964716741,2198,3162,72,1109,2021,Počet obyvatel s obvyklým pobytem,Praha 9
436338,965212348,3876,3162,72,1110,2021,Počet obyvatel s obvyklým pobytem,Praha 10
436404,965294490,3100,3162,72,1111,2021,Počet obyvatel s obvyklým pobytem,Praha 11
436470,964964283,2591,3162,72,1112,2021,Počet obyvatel s obvyklým pobytem,Praha 12
436536,964799197,2725,3162,72,1113,2021,Počet obyvatel s obvyklým pobytem,Praha 13
436602,964881307,2300,3162,72,1114,2021,Počet obyvatel s obvyklým pobytem,Praha 14
436668,965129167,2051,3162,72,1115,2021,Počet obyvatel s obvyklým pobytem,Praha 15
436734,965294616,1226,3162,72,1116,2021,Počet obyvatel s obvyklým pobytem,Praha 16
436800,965294742,1227,3162,72,1117,2021,Počet obyvatel s obvyklým pobytem,Praha 17
436866,965295129,1288,3162,72,1118,2021,Počet obyvatel s obvyklým pobytem,Praha 18
436932,964716293,670,3162,72,1119,2021,Počet obyvatel s obvyklým pobytem,Praha 19
436998,965294868,736,3162,72,1120,2021,Počet obyvatel s obvyklým pobytem,Praha 20
437064,964964172,1047,3162,72,1121,2021,Počet obyvatel s obvyklým pobytem,Praha 21
437130,965212353,948,3162,72,1122,2021,Počet obyvatel s obvyklým pobytem,Praha 22

In [75]:
df_okresy_praha = pandas.concat([df_okresy, df_praha])  # kontrola: 76 + 22 = 98
df_okresy_praha

,idhod,hodnota,ukaz_kod,uzemi_cis,uzemi_kod,sldb_rok,ukaz_txt,uzemi_txt
438714,964632166,4628,3162,101,40169,2021,Počet obyvatel s obvyklým pobytem,Benešov
438780,964704572,4485,3162,101,40177,2021,Počet obyvatel s obvyklým pobytem,Beroun
438846,964675015,7941,3162,101,40185,2021,Počet obyvatel s obvyklým pobytem,Kladno
438912,964703858,4882,3162,101,40193,2021,Počet obyvatel s obvyklým pobytem,Kolín
438978,964618666,3332,3162,101,40207,2021,Počet obyvatel s obvyklým pobytem,Kutná Hora
...,...,...,...,...,...,...,...,...
436866,965295129,1288,3162,72,1118,2021,Počet obyvatel s obvyklým pobytem,Praha 18
436932,964716293,670,3162,72,1119,2021,Počet obyvatel s obvyklým pobytem,Praha 19
436998,965294868,736,3162,72,1120,2021,Počet obyvatel s obvyklým pobytem,Praha 20
437064,964964172,1047,3162,72,1121,2021,Počet obyvatel s obvyklým pobytem,Praha 21
437130,965212353,948,3162,72,1122,2021,Počet obyvatel s obvyklým pobytem,Praha 22

### Ukládám finální tabulku okresů + pražských správních obvodů
(= 98 ř.)

In [77]:
df_okresy_praha = df_okresy_praha.reset_index(drop=True)  # resetuju index
df_okresy_praha

,idhod,hodnota,ukaz_kod,uzemi_cis,uzemi_kod,sldb_rok,ukaz_txt,uzemi_txt
0,964632166,4628,3162,101,40169,2021,Počet obyvatel s obvyklým pobytem,Benešov
1,964704572,4485,3162,101,40177,2021,Počet obyvatel s obvyklým pobytem,Beroun
2,964675015,7941,3162,101,40185,2021,Počet obyvatel s obvyklým pobytem,Kladno
3,964703858,4882,3162,101,40193,2021,Počet obyvatel s obvyklým pobytem,Kolín
4,964618666,3332,3162,101,40207,2021,Počet obyvatel s obvyklým pobytem,Kutná Hora
...,...,...,...,...,...,...,...,...
93,965295129,1288,3162,72,1118,2021,Počet obyvatel s obvyklým pobytem,Praha 18
94,964716293,670,3162,72,1119,2021,Počet obyvatel s obvyklým pobytem,Praha 19
95,965294868,736,3162,72,1120,2021,Počet obyvatel s obvyklým pobytem,Praha 20
96,964964172,1047,3162,72,1121,2021,Počet obyvatel s obvyklým pobytem,Praha 21
97,965212353,948,3162,72,1122,2021,Počet obyvatel s obvyklým pobytem,Praha 22

In [78]:
df_okresy_praha.to_csv('teenageri_okresy.csv')